/*ziye

å…·ä½“æ–¹æ³•è¯·çœ‹: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions


githubåœ°å€ https://github.com/ziye66666
TGé¢‘é“åœ°å€  https://t.me/ziyescript
TGäº¤æµç¾¤   https://t.me/joinchat/AAAAAE7XHm-q1-7Np-tF3g
boxjsé“¾æ¥  https://raw.githubusercontent.com/ziye66666/JavaScript/main/Task/ziye.boxjs.json



âš ï¸âš ï¸âš ï¸ç‰¹åˆ«é‡è¦,åŠ¡å¿…è¿›è¡Œæ›¿æ¢æ“ä½œï¼Œä¸å¾—ä½¿ç”¨åŸä½œè€…åœ°å€

 ä»¥è´¦å·ABC  
 ä»“åº“åœ°å€ https://github.com/ABC/JavaScript   
 æ–‡ä»¶åœ°å€   https://raw.githubusercontent.com/ABC/JavaScript/main/Task/xiaole.js    ä¸ºä¾‹ 


ä¸»è¦æ›¿æ¢çš„å­—ç¬¦ğŸ‘‡


å°ä¹        //jsåå­—
0 0-15    //å®šæ—¶ï¼Œå¦‚åŒ—äº¬æ—¶é—´8åˆ°23ç‚¹ï¼Œè®¾ç½®0-15
XL_URL    //ç¯å¢ƒå˜é‡ä¹‹ä¸€ï¼Œ45è¡Œå¤„è‡ªè¡Œæ·»åŠ å…¶ä»–
ABC        //è´¦å·å
JavaScript       //ä»“åº“å
Task/xiaole.js    //å­æ–‡ä»¶åœ°å€


*/

name: è¿”åˆ©2

on:
  workflow_dispatch:
  schedule:
     - cron: '0 2,15 * * *'
  watch:
    types: started
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    env:
        FL_flwURL: ${{ secrets.FL_flwURL }}
        FL_flwHEADER: ${{ secrets.FL_flwHEADER}}		
        FL_flwspBODY: ${{ secrets.FL_flwspBODY}}		
        FL_flwqwBODY: ${{ secrets.FL_flwqwBODY}}	
        FL_CASH: ${{ secrets.FL_CASH}}	
        FL_DHCASH: ${{ secrets.FL_DHCASH}}	
        FL_flwydBODY: ${{ secrets.FL_flwydBODY}}	
        
    steps:
      - name: Checkout
        run: |
          git clone https://github.com/xinjunxin/flw.git ~/JavaScript
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: npm install
        if: env.XL_URL
        run: |
          cd ~/JavaScript
          npm install
      - name: 'è¿è¡Œ ã€è¿”åˆ©2ã€‘'
        if: env.XL_URL
        run: |
          cd ~/JavaScript
          node Task/flw.js
        env:
          
          PUSH_KEY: ${{ secrets.PUSH_KEY }}
          BARK_PUSH: ${{ secrets.BARK_PUSH }}
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_USER_ID: ${{ secrets.TG_USER_ID }}
          BARK_SOUND: ${{ secrets.BARK_SOUND }}
          DD_BOT_TOKEN: ${{ secrets.DD_BOT_TOKEN }}
          DD_BOT_SECRET: ${{ secrets.DD_BOT_SECRET }}

    
